name: emb-venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - lightning=2.4.0
  - xarray=2024.9.0
  - zarr=2.18.3
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - pip

  - pip:
      - spyndex==0.6.0
